---
- name: Debian | Set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: Debian | Install wget
  apt:
    pkg: wget
    state: latest

- name: add new relic ppa
  shell: echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | sudo tee /etc/apt/sources.list.d/newrelic.list    

- name: add new relic ppa
  shell: wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -

- name: Debian | Install New Relic PHP Agent
  apt:
    pkg: newrelic-php5
    state: latest
  notify:
    - Run New Relic Installer